### ISSUE TITLE
Improve Helm Charts

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/sldt-digital-twin-registry#129]
**Is your feature request related to a problem? Please describe.**
The helm charts can be improved to provide more flexibility and to follow more the best practice guidelines (https://helm.sh/docs/chart_best_practices/templates/).

**Points to improve**
- [x] Use the `_helpers.tpl` and define functions for the following points. #281 
  - Chart Name (`registry.name`)
  - Fully qualified app name (`registry.fullname`)
  - Chart name + version (`registry.chart`)
  - Labels (`registry.labels`)
  - SelectorLabels (`registry.selectorLabels`)
- [x] Provide possibility to define the security contexts of the deployment & pod #311 
- [ ] #312
- [x] Provide possibility to customize liveness & readinessProbe
- [ ] In regards to #127 it would be also beneficial to provide a `ServiceMonitor` resource
- [x] Remove unneeded variables #281 

**Open points**
- Can the registry been scaled horizontally? If yes, the helm chart should also provide an HorizontalPodAutoscaler resource.

**Comment by agg3fe** [comment]
Hi,
Thanks for reporting. We will analyse this issue. Will provide you the feedback on it.

**Comment by ds-lcapellino** [comment]
Is there any update on this issue? 
We at TraceX can't properly sync our Argo environment because of the hard coded metadata.name attribute in: 
- test-credentials.yaml
- test-script-configmap.yaml
- init-script-configmap.yaml

If we run two instances of registries in our ArgoCD they somehow always override each other while syncing. I guess it's because of the above-mentioned hard coded name attributes.

**Comment by tunacicek** [comment]
Hi together, 
The following PR has been created and is under review.
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/281

**Comment by thomas-henn** [comment]
https://github.com/eclipse-tractusx/sig-release/issues/347

**Comment by tunacicek** [comment]
@ds-lcapellino The PR is merged and the changes are available with helm release version 0.4.0

**Comment by tunacicek** [comment]
@florianrusch-zf : for the security Context the following PR is created: 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/311/files

**Comment by tunacicek** [comment]
@florianrusch-zf : If it is ok for you, i would close this issue. For the other open points we have the following issues: 
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/311
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/312
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/127
