### ISSUE TITLE
EDC extension

### ISSUE THREAD

**Issue by RazvanZmau** [eclipse-tractusx/sldt-digital-twin-registry#352]
[x ] Move DTR EDC extension to SLDT DTR Github repository.
[ x] Adjust the EDC extension to the new EDC data flow. Use the EDC signaling functionality.
[ x] Prepare publish artifacts to Maven central
[ x] Build custom EDC image for own SLDT env test. 
[x ] To be written also a documentation for this functionality.

**Comment by RazvanZmau** [comment]
Linked to https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/288

**Comment by istvan-nagy-epam** [comment]
Hi @RazvanZmau could you please assign me?

**Comment by istvan-nagy-epam** [comment]
#### Tasks
- [ ] Move DTR EDC extension to SLDT DTR Github repository.
- [ ] Adjust the EDC extension to the new EDC data flow. Use the EDC signaling functionality.
- [ ] Prepare publish artifacts to Maven central
- [ ] Build custom EDC image for own SLDT env test.
- [ ] To be written also a documentation for this functionality.
