### ISSUE TITLE
QG4 System Team checks Release 3.1.0

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sldt-digital-twin-registry#88]
### Please keep this issue open until QG 4 is concluded and will be managed by the Issue Creator! 
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

Product Name: SLDT Digital Twin Registry
Product Owner: Thomas Henn
Dev SPOC: @tunacicek @LuLeRoemer 
Helm Chart Version: <s>`0.2.13`</s> →   0.2.17
App Version: <s>`0.2.0-M9-multi-tenancy`</s> → 0.2.0-M12-multi-tenancy

Chart Version: 0.2.17 (once this PR has been merged: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/115)
App version: 0.2.0-M12-multi-tenancy

QG4 Approval: yes/no

##### TRG 1.01
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] an appropriate `README.md` file
###### TRG 1.02
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
- [x] an appropriate `INSTALL.md` #92
###### TRG 1.03
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3
- [x] an appropriate `CHANGELOG.md`
  - [x] the versioning itself follows [semantic versioning](https://semver.org/)
##### TRG 2.01
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
- [x] default branch is named `main`
##### TRG 2.03
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
- [x] `/docs` directory
- [x] must contain detailed product related documentation for the Tractus-X product #93 
- [x] `/charts` directory
- [x] must contain the Helm chart for the Tractus-X product IF available
- [x] `AUTHORS.md` file (optional)
- [x] #106
- [x] `CONTRIBUTING.md` file
- [x] `DEPENDENCIES` file(s)
- [x] run Dash Tool to update Dependencies File #102
- [x] `LICENSE` file
- [x] `NOTICE.md` file
- [x] `SECURITY.md` file
##### TRG 2.04
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4
- [x] a Leading product repository
- [x] repository name must be _productname_ without prefix or suffix
- [x] should contain the release
- [x] references/urls to the product's other repositories
- [x] might contain product helm chart
- [x] README.md: contains the urls for the backend and frontend applications
##### TRG 2.05
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
- [x] `.tractusx` metafile is present in the root of the repository #94
- [x] file has a proper format #112
##### TRG 3.02
https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2
- [x] if data persistence is needed in Kubernetes the use of PersistentVolume and PersistentVolumeClaim resource #95 
##### TRG 4.01
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1
- [x] All images must be tagged following [semantic versioning](https://semver.org/)
- [x] container is labeled correctly additionally to the latest tag
##### TRG 4.02
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2
- [x] must add a section to your top level `README.md` file, that contains information about the used base image
- [x] Java, Kotlin, ... if JVM based language use base image from [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)
##### TRG 4.03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3
- [x] image has `USER` command to specify a non-root user to run the container
- [x] `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
##### TRG 4.05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-5
- [x] released image must be present on `GitHub Package registry` or `Dockerhub`
##### TRG 5.01
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
- [x] Helm chart must be released
- [x] appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
- [x] must not contain any environment specific `values-xyz.yaml`
- [x] `values.yaml` file must contain proper default values/placeholders
- [x] No hostname provided for ingress
- [x] Ingress is disabled
- [x] No references to any secret engine service (e.g.: Hashicorp Vault)
- [x] Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
- [x] Image tag is set to the `Chart.yaml` `appVersion` property
- [x] must be deployable to any environment without overwriting default values with a simple helm install command
- [x] dependencies have to be declared in Chart.yaml NOT requirements.yml
- [x] recommended use GitHub [Chart Releaser Action](https://github.com/helm/chart-releaser-action)
##### TRG 5.02
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
- [x] Helm chart location inside Git repository in `/charts` directory
- [x] chart file structure #101 
``` markdown
charts/ 
    chartNameA/
      Chart.yaml
      ... 
    chartNameB/
      Chart.yaml
      ...
AUTHORS.md 
DEPENDENCIES.md 
LICENCE 
README.md 
```
- [x] each file must contain the [Apache 2.0 Licence](https://github.com/catenax-ng/foss-example/blob/main/general/LICENSE)
- [x] latest tag is not used in helm chart be default
##### TRG 5.04
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
- [x] CPU and memory limits and requests are properly set #103
##### TRG 5.06
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06
- [x] every startup configuration aspect of your application must be configurable through the Helm chart (ingress class, tls, labels, annotations, database, secrets, persistence, env variables)
##### TRG 5.07
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07
- [x] if dependencies are present in the `Chart.yaml` they are properly configured
##### TRG 5.08
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08
- [x] a product has a single deployable helm chart that contains all components (backend, frontend, etc.)
- [x] name of the Chart should be just the product-name without prefix or suffix
- [x] values file should contain all available variables (even from subcharts) with default values and comments about what they do
- [x] helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values)
- [x] helm test runs without errors

#### Testing
- [x] installed and running on pre-prod without errors #100 

#### Information Sharing

**Comment by tunacicek** [comment]
Hi @FaGru3n ,
sure. 

Product Name:  Digital Twin Registry  
Product Owner:  Thomas Henn
Dev SPOC:  Lukas Römer, Tunahan Cicek
Helm Chart Version:  0.2.13
App Version: 0.2.0-M9-multi-tenancy  
QG4 Approval: no

**Comment by FaGru3n** [comment]
Hi @LuLeRoemer and @tunacicek 

little update for #106

**Comment by LuLeRoemer** [comment]
#102 is already fixed

**Comment by bs-jokri** [comment]
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/93 is fixed now

**Comment by bs-jokri** [comment]
#94 is fixed now

**Comment by bs-jokri** [comment]
#95 is not valid (check comment in issue for details)

**Comment by bs-jokri** [comment]
#101 is not valid (check comment in issue for details)

**Comment by bs-jokri** [comment]
https://github.com/eclipse-tractusx/sldt-digital-twin-registry/issues/103 needs further investigations and will not be closed for now

**Comment by FaGru3n** [comment]
Hi @LuLeRoemer @bs-jokri  

please inform us which current tag we have to test after changes

Helm Chart Version: <s>`0.2.13`</s> →  ?
App Version: <s>`0.2.0-M9-multi-tenancy`</s> → ?

**Comment by LuLeRoemer** [comment]
@FaGru3n 
Chart Version: 0.2.17 (once this PR has been merged: https://github.com/eclipse-tractusx/sldt-digital-twin-registry/pull/115)
App version: 0.2.0-M12-multi-tenancy

**Comment by FaGru3n** [comment]
succesfully synced on argo pre-prod
